services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: localhost  
    ports:
      - "80:80"  
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306           
      - MYSQL_DATABASE=SoKHCNProject
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
    volumes:
      - ./uploads:/app/uploads  
    restart: unless-stopped 
